# configs/settings_local.yaml
env: local

redis:
  host: 4.1.9.10
  port: 6379
  db: 0

models:
  insightface_root: /workspace
  insightface_name: buffalo_l
  yolo_path: /workspace/models

server:
  host: 0.0.0.0
  port: 5011
  workers: 1           # gunicorn workers 数量，默认 1
  threads: 5         # 每个 worker 的线程数，默认 5
  timeout: 0         # 请求超时时间，0 表示不超时，适合长连接/流式接口

logging:
  dir: /workspace/logs  # 容器内日志目录（会被 docker-compose 挂载出来）
  level: info        # 日志级别，可选 debug / info / warning / error

i18n:
  default_language: zh-CN
  fallback_language: en
  supported_languages:
    - en
    - zh-CN

minio:
  endpoint: 192.168.130.162:9100
  access_key: minioadmin
  secret_key: minioadmin123
  bucket: camera-checkout
  secure: false
  max_frames_per_stream: 1000
  trim_interval: 400
  use_intrussion_suffix: true
  save_mode: all
  sample_fps: 1.0
  jpeg_quality: 85

stream:
  ws_send_mode: all

monitoring:
  enabled: true
  history_size: 240
  frame_history: 120

